name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'REL1_37'

    - run: |
        submodule=$(echo $(echo ${GITHUB_HEAD_REF} | cut -d'/' -f4,5 ) | cut -d'-' -f1 )
        git submodule update --init $submodule
        git pull https://github.com/${GITHUB_REPOSITORY} ${GITHUB_HEAD_REF}
        list=$(git -c color.diff=false diff --submodule=diff $submodule | sed -n -e s/^diff\ --git\ a\\///p)
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        codechangeFiles="(extensions|skins)\/.*\/(.*\.php|extension\.json|skin\.json)"
        buildFiles="(extensions|skins)\/.*\/(\.github\/.*|tests\/.*|composer(\.json|\.lock)|package(\-lock)?\.json)"
        i18nFiles="(extensions|skins)\/.*\/i18n\/.*\.json"

        for file in $list; do
          if [ $(echo $file | cut -d'/' -f1 ) != b ]; then
            if [[ $file =~ $codechangeFiles ]] && [[ ! $file =~ $buildFiles ]]; then
              curl \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
              https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/$pull_number/labels \
              -d '{"labels":["codechange"]}'
            fi

            if [[ $file =~ $buildFiles ]]; then
              curl \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
              https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/$pull_number/labels \
              -d '{"labels":["build"]}'
            fi

            if [[ $file =~ $i18nFiles ]]; then
              curl \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
              https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/$pull_number/labels \
              -d '{"labels":["i18n"]}'
            fi
          fi
        done
